In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
pd.set_option('display.max_columns', None)

In [18]:
# Load the dataset
df_bank_csv = pd.read_csv('bank-additional.csv')
display(df_bank_csv.describe())

,Unnamed: 0,age,default,housing,loan,duration,campaign,pdays,previous,emp.var.rate,latitude,longitude
count,43000.000000,37880.000000,34019.000000,41974.000000,41974.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000
mean,20651.099047,39.977112,0.000088,0.535998,0.155620,257.739279,2.567233,962.330953,0.174023,0.077128,36.856697,-95.939067
std,11868.770913,10.437957,0.009390,0.498708,0.362499,258.666033,2.772294,187.260394,0.497366,1.573898,7.225948,16.752282
min,0.000000,17.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,-3.400000,24.396000,-124.997000
25%,10381.750000,32.000000,0.000000,0.000000,0.000000,102.000000,1.000000,999.000000,0.000000,-1.800000,30.614750,-110.494250
50%,20642.500000,38.000000,0.000000,1.000000,0.000000,179.000000,2.000000,999.000000,0.000000,1.100000,36.761000,-95.899500
75%,30930.250000,47.000000,0.000000,1.000000,0.000000,319.000000,3.000000,999.000000,0.000000,1.400000,43.113250,-81.427750
max,41187.000000,98.000000,1.000000,1.000000,1.000000,4918.000000,56.000000,999.000000,7.000000,1.400000,49.384000,-66.937000

In [19]:
# Load the xlsx dataset
# Cargar todas las hojas, esto nos devuelve un diccionario con todas las hojas
hojas_dict = pd.read_excel('customer-details.xlsx', sheet_name=None)
print(hojas_dict.keys())  # Imprime los nombres de las hojas para verificar

dict_keys(['2012', '2013', '2014'])

In [ ]:
lista_dfs = []

for nombre_hoja, df in hojas_dict.items():
    df["year"] = nombre_hoja
    lista_dfs.append(df)

df_final = pd.concat(lista_dfs, ignore_index=True)

df_final['year'] = df_final['year'].astype(int)
df_final['month'] = df_final['Dt_Customer'].dt.month

# Customer id como la primera columna
col = df_final.pop('Unnamed: 0')
df_final.insert(0, 'customer_id', col)

display(df_final.head(10))
display(df_final.info())

,customer_id,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID,year,month
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079,2012,4
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097,2012,12
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b,2012,2
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e,2012,12
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,2012,6
5,5,143854,0,1,2012-01-24,26,d63ede72-0b6d-45b1-8872-385ac6897f65,2012,1
6,6,76439,1,0,2012-08-15,3,5e3483e5-236d-437d-8351-541f9d09b9dd,2012,8
7,7,159686,1,1,2012-12-10,21,87fdc08b-30ae-4dab-803f-561ecdf27ff0,2012,12
8,8,179933,0,0,2012-08-22,18,87b79988-2be5-419d-88f4-56655852c565,2012,8
9,9,77504,1,0,2012-02-09,18,ea6b7d04-9271-4c0a-a01f-07795d164aba,2012,2

<class 'pandas.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[us]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  str
 7   year               43170 non-null  int64
 8   month              43170 non-null  int32
dtypes: datetime64[us](1), int32(1), int64(6), str(1)
memory usage: 4.3 MB

None

In [22]:
df_final.describe()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,year
count,43170.000000,43170.000000,43170.000000,43170.000000,43170,43170.000000,43170.000000
mean,7916.022469,93227.389622,1.004749,0.998633,2013-05-11 22:09:47.407922,16.591290,2012.860435
min,0.000000,5841.000000,0.000000,0.000000,2012-01-01 00:00:00,1.000000,2012.000000
25%,3597.000000,49608.000000,0.000000,0.000000,2012-07-16 00:00:00,9.000000,2012.000000
50%,7194.500000,93009.500000,1.000000,1.000000,2013-03-01 00:00:00,17.000000,2013.000000
75%,11705.750000,136740.500000,2.000000,2.000000,2014-03-28 00:00:00,25.000000,2014.000000
max,20114.000000,180802.000000,2.000000,2.000000,2014-12-31 00:00:00,32.000000,2014.000000
std,5228.248885,50498.181989,0.815996,0.816008,NaN,9.241769,0.879132

In [60]:
display(df_bank_csv.info())
# nulls en age, job, marital, education, default, housing, loan, cons.price.idx, euribor3m, date
display(df_bank_csv.isna().sum())
display(df_bank_csv['age'].value_counts())
display(df_bank_csv.sample(5))

# vamos a comparar si coinciden los customer_id entre ambos datasets
customer_ids_bank = set(df_bank_csv['customer_id'])
customer_ids_final = set(df_final['customer_id'])
customer_ids_intersection = customer_ids_bank.intersection(customer_ids_final)
print(f"Customer IDs en bank-additional.csv: {len(customer_ids_intersection)}")
# podemos obtener los customer_id que no se comparten entre datasets

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     43000 non-null  str
 1   age             37880 non-null  float64
 2   job             42655 non-null  str
 3   marital         42915 non-null  str
 4   education       41193 non-null  str
 5   default         43000 non-null  object
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  str
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  str
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  str
 16  cons.conf.idx   43000 non-null  str
 17  euribor3m       15 non-null     float64
 18  nr.employed     43000 non-null  str
 19  y               43000 non-null  str
 20  date            42752 non-null  str
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
dtypes: float64(7), int64(4), object(1), str(11)
memory usage: 12.3+ MB

None

customer_id           0
age                5120
job                 345
marital              85
education          1807
default               0
housing            1026
loan               1026
contact               0
duration              0
campaign              0
pdays                 0
previous              0
poutcome              0
emp.var.rate          0
cons.price.idx      471
cons.conf.idx         0
euribor3m         42985
nr.employed           0
y                     0
date                248
latitude              0
longitude             0
dtype: int64

age
31.0    1810
33.0    1704
32.0    1672
36.0    1649
34.0    1608
        ...
98.0       2
89.0       2
95.0       1
87.0       1
94.0       1
Name: count, Length: 78, dtype: int64

,customer_id,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude
12738,48f7ca0a-b897-4649-a1ce-db5dd584399a,59.0,housemaid,MARRIED,basic.4y,unknown,NaN,NaN,cellular,202,2,999,0,NONEXISTENT,1.4,"93,918","-42,7",NaN,"5228,1",no,29-octubre-2017,30.413,-97.713
31095,8273c87c-d05d-4cad-876a-ce84fc87f4b9,35.0,technician,MARRIED,professional.course,0.0,0.0,0.0,cellular,66,2,999,0,NONEXISTENT,-1.8,"92,893","-46,2",NaN,"5099,1",no,14-mayo-2015,35.353,-93.871
13215,1b35e431-10d5-4b79-ba41-5ad0bd830e85,51.0,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,cellular,145,1,999,0,NONEXISTENT,1.4,"93,918","-42,7",NaN,"5228,1",no,1-octubre-2017,37.265,-67.625
28024,1e16d19a-cae8-4c70-9e90-deb438eed7f4,29.0,technician,SINGLE,professional.course,0.0,1.0,0.0,cellular,740,3,999,0,NONEXISTENT,-1.8,"93,075","-47,1",NaN,"5099,1",yes,10-noviembre-2019,38.289,-93.577
7013,c9407a39-8bfe-43da-917b-6b1747b348bd,51.0,admin.,MARRIED,high.school,0.0,1.0,0.0,telephone,431,2,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,6-enero-2019,33.705,-113.502

Customer IDs en bank-additional.csv: 0

In [ ]:
col = df_bank_csv.pop('id_')
df_bank_csv.insert(0, 'customer_id', col)
df_bank_csv.drop(columns=['Unnamed: 0'], inplace=True)

In [50]:
#display(df_bank_csv[df_bank_csv['date'].isna()])

# Customer id como la primera columna

display(df_bank_csv['default'].value_counts(dropna=False))

df_bank_csv['default'] = df_bank_csv['default'].fillna('unknown')

display(df_bank_csv.head(10))

default
0.0        34016
unknown     8981
1.0            3
Name: count, dtype: int64

,customer_id,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude
0,089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233
1,e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,unknown,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923
2,3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847
3,9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308
4,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463
5,d63ede72-0b6d-45b1-8872-385ac6897f65,45.0,services,MARRIED,basic.9y,unknown,0.0,0.0,telephone,198,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,26-septiembre-2015,24.689,-101.643
6,5e3483e5-236d-437d-8351-541f9d09b9dd,59.0,admin.,MARRIED,professional.course,0.0,0.0,0.0,telephone,139,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,25-enero-2019,31.456,-94.561
7,87fdc08b-30ae-4dab-803f-561ecdf27ff0,NaN,blue-collar,MARRIED,NaN,unknown,0.0,0.0,telephone,217,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,25-septiembre-2017,46.871,-122.235
8,87b79988-2be5-419d-88f4-56655852c565,24.0,technician,SINGLE,professional.course,0.0,1.0,0.0,telephone,380,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,18-enero-2018,44.632,-85.811
9,ea6b7d04-9271-4c0a-a01f-07795d164aba,25.0,services,SINGLE,high.school,0.0,1.0,0.0,telephone,50,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2-noviembre-2016,30.297,-117.382

In [ ]:
# --- Revisar euribor en dataset bank ---
display(df_bank_csv['euribor3m'].sample(10))
display(df_bank_csv['euribor3m'].value_counts(dropna=False))

df_bank_csv['euribor3m'] = pd.to_numeric(df_bank_csv['euribor3m'], errors='coerce')

display(df_bank_csv['euribor3m'].describe())
print("NaN:", df_bank_csv['euribor3m'].isna().sum())

# --- Cargar y limpiar dataset de euribor ---
df_euribor = (
    pd.read_csv('euribor.csv', sep=';')
    .drop(columns=['Unnamed: 3'])
)

df_euribor['Mes'] = df_euribor['Mes'].str.lower()

df_euribor['Valor'] = (
    df_euribor['Valor']
    .str.replace('%', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

df_euribor['match'] = df_euribor['Mes'] + '-' + df_euribor['Año'].astype(str)

# --- Preparar dataset de pruebas ---
df_trials = df_bank_csv.copy()

df_trials['euribor3m_date'] = (
    df_trials['date'].str.split('-').str[1] +
    '-' +
    df_trials['date'].str.split('-').str[2]
)

display(df_trials[['euribor3m']].sample(10))

# --- Unir datasets ---
df_trials = (
    df_trials
    .merge(
        df_euribor[['match', 'Valor']],
        left_on='euribor3m_date',
        right_on='match',
        how='left'
    )
    .drop(columns='match')
)

df_bank_csv['euribor3m'] = df_trials['Valor']

display(df_bank_csv.head())

5017     -0.17
37460     0.18
39554    -0.10
848      -0.06
13111    -0.11
32714    -0.19
13104    -0.19
39826    -0.05
30103    -0.01
17525    -0.13
Name: euribor3m, dtype: str

euribor3m
-0.19    5685
-0.11    3559
-0.15    2835
-0.01    2815
-0.18    2196
-0.17    2113
-0.13    2103
-0.07    1439
0.17     1428
-0.06    1426
-0.12    1408
0.16     1374
0.21      766
-0.28     763
-0.16     743
-0.03     734
-0.27     725
0.18      719
-0.10     716
0.06      716
0.15      713
0.13      712
0.04      711
-0.36     710
-0.31     709
-0.34     709
0.26      709
-0.05     706
0.30      706
-0.08     702
0.08      701
-0.26     701
NaN       248
Name: count, dtype: int64

count    42752.000000
mean        -0.080563
std          0.149198
min         -0.360000
25%         -0.180000
50%         -0.120000
75%         -0.010000
max          0.300000
Name: euribor3m, dtype: float64

NaN: 248

       euribor3m
3850        0.17
8082        0.08
4404       -0.19
9704       -0.11
2494       -0.11
4192       -0.06
36388      -0.15
39556      -0.11
14276      -0.19
38945       0.18

,customer_id,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude
0,089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",-0.36,5191,no,2-agosto-2019,41.495,-71.233
1,e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,unknown,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",-0.06,5191,no,14-septiembre-2016,34.601,-83.923
2,3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",-0.11,5191,no,15-febrero-2019,34.939,-94.847
3,9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",0.08,5191,no,29-noviembre-2015,49.041,-70.308
4,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",-0.10,5191,no,29-enero-2017,38.033,-104.463