In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
pd.set_option('display.max_columns', None)

In [2]:
# Load the dataset
df_bank_csv = pd.read_csv('bank-additional.csv')
display(df_bank_csv.describe())

,Unnamed: 0,age,default,housing,loan,duration,campaign,pdays,previous,emp.var.rate,latitude,longitude
count,43000.000000,37880.000000,34019.000000,41974.000000,41974.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000
mean,20651.099047,39.977112,0.000088,0.535998,0.155620,257.739279,2.567233,962.330953,0.174023,0.077128,36.856697,-95.939067
std,11868.770913,10.437957,0.009390,0.498708,0.362499,258.666033,2.772294,187.260394,0.497366,1.573898,7.225948,16.752282
min,0.000000,17.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,-3.400000,24.396000,-124.997000
25%,10381.750000,32.000000,0.000000,0.000000,0.000000,102.000000,1.000000,999.000000,0.000000,-1.800000,30.614750,-110.494250
50%,20642.500000,38.000000,0.000000,1.000000,0.000000,179.000000,2.000000,999.000000,0.000000,1.100000,36.761000,-95.899500
75%,30930.250000,47.000000,0.000000,1.000000,0.000000,319.000000,3.000000,999.000000,0.000000,1.400000,43.113250,-81.427750
max,41187.000000,98.000000,1.000000,1.000000,1.000000,4918.000000,56.000000,999.000000,7.000000,1.400000,49.384000,-66.937000

In [3]:
# Load the xlsx dataset
# Cargar todas las hojas, esto nos devuelve un diccionario con todas las hojas
hojas_dict = pd.read_excel('customer-details.xlsx', sheet_name=None)
print(hojas_dict.keys())  # Imprime los nombres de las hojas para verificar

dict_keys(['2012', '2013', '2014'])

In [4]:
lista_dfs = []

for nombre_hoja, df in hojas_dict.items():
    df["year"] = nombre_hoja
    lista_dfs.append(df)

df_final = pd.concat(lista_dfs, ignore_index=True)

df_final['year'] = df_final['year'].astype(int)
df_final['month'] = df_final['Dt_Customer'].dt.month

# Customer id como la primera columna
col = df_final.pop('Unnamed: 0')
df_final.insert(0, 'customer_id', col)

display(df_final.head(10))
display(df_final.info())

,customer_id,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID,year,month
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079,2012,4
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097,2012,12
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b,2012,2
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e,2012,12
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,2012,6
5,5,143854,0,1,2012-01-24,26,d63ede72-0b6d-45b1-8872-385ac6897f65,2012,1
6,6,76439,1,0,2012-08-15,3,5e3483e5-236d-437d-8351-541f9d09b9dd,2012,8
7,7,159686,1,1,2012-12-10,21,87fdc08b-30ae-4dab-803f-561ecdf27ff0,2012,12
8,8,179933,0,0,2012-08-22,18,87b79988-2be5-419d-88f4-56655852c565,2012,8
9,9,77504,1,0,2012-02-09,18,ea6b7d04-9271-4c0a-a01f-07795d164aba,2012,2

<class 'pandas.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[us]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  str
 7   year               43170 non-null  int64
 8   month              43170 non-null  int32
dtypes: datetime64[us](1), int32(1), int64(6), str(1)
memory usage: 4.3 MB

None

In [5]:
df_final.describe()

,customer_id,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,year,month
count,43170.000000,43170.000000,43170.000000,43170.000000,43170,43170.000000,43170.000000,43170.000000
mean,7916.022469,93227.389622,1.004749,0.998633,2013-05-11 22:09:47.407922,16.591290,2012.860435,6.522770
min,0.000000,5841.000000,0.000000,0.000000,2012-01-01 00:00:00,1.000000,2012.000000,1.000000
25%,3597.000000,49608.000000,0.000000,0.000000,2012-07-16 00:00:00,9.000000,2012.000000,4.000000
50%,7194.500000,93009.500000,1.000000,1.000000,2013-03-01 00:00:00,17.000000,2013.000000,7.000000
75%,11705.750000,136740.500000,2.000000,2.000000,2014-03-28 00:00:00,25.000000,2014.000000,10.000000
max,20114.000000,180802.000000,2.000000,2.000000,2014-12-31 00:00:00,32.000000,2014.000000,12.000000
std,5228.248885,50498.181989,0.815996,0.816008,NaN,9.241769,0.879132,3.447095

In [6]:
display(df_bank_csv.info())
# nulls en age, job, marital, education, default, housing, loan, cons.price.idx, euribor3m, date
display(df_bank_csv.isna().sum())
display(df_bank_csv['age'].value_counts())
display(df_bank_csv.sample(5))

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  str
 3   marital         42915 non-null  str
 4   education       41193 non-null  str
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  str
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  str
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  str
 16  cons.conf.idx   43000 non-null  str
 17  euribor3m       33744 non-null  str
 18  nr.employed     43000 non-null  str
 19  y               43000 non-null  str
 20  date            42752 non-null  str
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  str
dtypes: float64(7), int64(5), str(12)
memory usage: 12.8 MB

None

Unnamed: 0           0
age               5120
job                345
marital             85
education         1807
default           8981
housing           1026
loan              1026
contact              0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx     471
cons.conf.idx        0
euribor3m         9256
nr.employed          0
y                    0
date               248
latitude             0
longitude            0
id_                  0
dtype: int64

age
31.0    1810
33.0    1704
32.0    1672
36.0    1649
34.0    1608
        ...
98.0       2
89.0       2
95.0       1
87.0       1
94.0       1
Name: count, Length: 78, dtype: int64

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
11868,11965,43.0,blue-collar,MARRIED,basic.9y,0.0,0.0,0.0,telephone,89,4,999,0,NONEXISTENT,1.4,"94,465","-41,8","4,958","5228,1",no,10-agosto-2019,33.010,-72.589,1a3d5187-402f-4488-9240-42bee6b5851c
39493,39660,29.0,admin.,SINGLE,university.degree,0.0,0.0,0.0,cellular,216,1,3,3,SUCCESS,-1.8,"93,876",-40,"0,683","5008,7",yes,16-octubre-2016,46.472,-118.364,52175ffd-c2fb-44cf-9370-07816625e3b6
23182,23279,36.0,admin.,MARRIED,university.degree,NaN,1.0,0.0,cellular,155,11,999,0,NONEXISTENT,1.4,"93,444","-36,1","4,964","5228,1",no,6-marzo-2016,39.743,-121.779,c3c3a62f-775f-4e3d-b8c1-96c39a063149
5737,5834,37.0,self-employed,MARRIED,basic.9y,NaN,0.0,0.0,telephone,166,2,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,28-octubre-2016,45.364,-78.254,b0fc4373-9af8-435c-b95d-8c62985f1de5
31006,31150,35.0,services,MARRIED,high.school,NaN,1.0,0.0,cellular,404,1,999,1,FAILURE,-1.8,"92,893","-46,2","1,334","5099,1",no,20-diciembre-2017,32.052,-90.563,8a7497fc-8a3a-4f3c-a175-0d3a791ab71e

In [7]:
col = df_bank_csv.pop('id_')
df_bank_csv.insert(0, 'customer_id', col)
df_bank_csv.drop(columns=['Unnamed: 0'], inplace=True)

# vamos a comparar si coinciden los customer_id entre ambos datasets
customer_ids_bank = set(df_bank_csv['customer_id'])
customer_ids_final = set(df_final['customer_id'])
customer_ids_intersection = customer_ids_bank.intersection(customer_ids_final)
print(f"Customer IDs en bank-additional.csv: {len(customer_ids_intersection)}")
# podemos obtener los customer_id que no se comparten entre datasets

Customer IDs en bank-additional.csv: 0

## Default

In [8]:
# transformamos los datos NaN en 'unknown' para no alterar ni eliminar datos de 
# valor del dataset ya que estos son una parte importante de la población
display(df_bank_csv['default'].value_counts(dropna=False))

df_bank_csv['default'] = df_bank_csv['default'].fillna(-1).astype(float)

display(df_bank_csv.head(10))

default
0.0    34016
NaN     8981
1.0        3
Name: count, dtype: int64

,customer_id,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude
0,089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233
1,e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,-1.0,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923
2,3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847
3,9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308
4,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463
5,d63ede72-0b6d-45b1-8872-385ac6897f65,45.0,services,MARRIED,basic.9y,-1.0,0.0,0.0,telephone,198,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,26-septiembre-2015,24.689,-101.643
6,5e3483e5-236d-437d-8351-541f9d09b9dd,59.0,admin.,MARRIED,professional.course,0.0,0.0,0.0,telephone,139,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,25-enero-2019,31.456,-94.561
7,87fdc08b-30ae-4dab-803f-561ecdf27ff0,NaN,blue-collar,MARRIED,NaN,-1.0,0.0,0.0,telephone,217,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,25-septiembre-2017,46.871,-122.235
8,87b79988-2be5-419d-88f4-56655852c565,24.0,technician,SINGLE,professional.course,0.0,1.0,0.0,telephone,380,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,18-enero-2018,44.632,-85.811
9,ea6b7d04-9271-4c0a-a01f-07795d164aba,25.0,services,SINGLE,high.school,0.0,1.0,0.0,telephone,50,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,2-noviembre-2016,30.297,-117.382

## Euríbor

In [9]:
# --- Revisar euribor en dataset bank ---
display(df_bank_csv['euribor3m'].sample(10))
display(df_bank_csv['euribor3m'].value_counts(dropna=False))

df_bank_csv['euribor3m'] = pd.to_numeric(df_bank_csv['euribor3m'], errors='coerce')

display(df_bank_csv['euribor3m'].describe())
print("NaN:", df_bank_csv['euribor3m'].isna().sum())

# --- Cargar y limpiar dataset de euribor ---
# he obtenido los datos históricos mensuales del euríbor y los he guardado en un csv
df_euribor = (
    pd.read_csv('euribor.csv', sep=';')
    .drop(columns=['Unnamed: 3'])
)

df_euribor['Mes'] = df_euribor['Mes'].str.lower()

df_euribor['Valor'] = (
    df_euribor['Valor']
    .str.replace('%', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

df_euribor['match'] = df_euribor['Mes'] + '-' + df_euribor['Año'].astype(str)

# --- Preparar dataset de pruebas ---
df_trials = df_bank_csv.copy()

df_trials['euribor3m_date'] = (
    df_trials['date'].str.split('-').str[1] +
    '-' +
    df_trials['date'].str.split('-').str[2]
)

display(df_trials[['euribor3m']].sample(10))

# --- Unir datasets ---
df_trials = (
    df_trials
    .merge(
        df_euribor[['match', 'Valor']],
        left_on='euribor3m_date',
        right_on='match',
        how='left'
    )
    .drop(columns='match')
)

df_bank_csv['euribor3m'] = df_trials['Valor']

df_bank_csv['euribor3m'] = df_bank_csv['euribor3m'].fillna(df_bank_csv['euribor3m'].mode())

display(df_bank_csv.head())

8108     4,864
33223    1,291
22854    4,965
17008    4,962
20319    4,966
23038      NaN
33478    1,281
35175     1,25
9355     4,967
29155    1,405
Name: euribor3m, dtype: str

euribor3m
NaN      9256
4,857    2287
4,962    2124
4,963    2019
4,961    1594
         ...
0,895       1
0,894       1
0,953       1
0,956       1
1,047       1
Name: count, Length: 310, dtype: int64

count    15.0
mean      1.0
std       0.0
min       1.0
25%       1.0
50%       1.0
75%       1.0
max       1.0
Name: euribor3m, dtype: float64

NaN: 42985

       euribor3m
40701        NaN
38878        NaN
18948        NaN
35607        NaN
36678        NaN
27856        NaN
38863        NaN
9807         NaN
338          NaN
36183        NaN

,customer_id,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude
0,089b39d8-e4d0-461b-87d4-814d71e0e079,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",-0.36,5191,no,2-agosto-2019,41.495,-71.233
1,e9d37224-cb6f-4942-98d7-46672963d097,57.0,services,MARRIED,high.school,-1.0,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",-0.06,5191,no,14-septiembre-2016,34.601,-83.923
2,3f9f49b5-e410-4948-bf6e-f9244f04918b,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",-0.11,5191,no,15-febrero-2019,34.939,-94.847
3,9991fafb-4447-451a-8be2-b0df6098d13e,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",0.08,5191,no,29-noviembre-2015,49.041,-70.308
4,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",-0.10,5191,no,29-enero-2017,38.033,-104.463

## Age

In [10]:
# revisamos age y convertimos todos los nulos a la media
display(df_bank_csv['age'].isna().sum())
display(df_bank_csv['age'].mean())  

df_bank_csv['age'] = df_bank_csv['age'].fillna(df_bank_csv['age'].mean())
df_bank_csv['age'] = df_bank_csv['age'].astype(int)

display(df_bank_csv['age'].isna().sum())

np.int64(5120)

np.float64(39.97711193241816)

np.int64(0)

## Date

In [11]:
# revisamos date y convertimos eliminamos los nulos ya que representan menos de un 1%
# de la población y no parecen seguir ningún patrón claro
display(df_bank_csv['date'].isna().sum())

df_bank_csv = df_bank_csv.dropna(subset=['date'])

display(df_bank_csv['date'].isna().sum())

np.int64(248)

np.int64(0)

## Job

In [12]:
# hacemos que los valores nulos como represantan una parte pequeña de la población
# los transformaremos a 'unknown' para no tener NaN en el dataset
display(df_bank_csv['job'].isna().sum())
display(df_bank_csv['job'].value_counts(dropna=False))

df_bank_csv['job'] = df_bank_csv['job'].fillna('unknown')

display(df_bank_csv['job'].value_counts(dropna=False))

np.int64(344)

job
admin.           10802
blue-collar       9605
technician        6984
services          4135
management        3036
retired           1782
entrepreneur      1509
self-employed     1483
housemaid         1117
unemployed        1059
student            896
NaN                344
Name: count, dtype: int64

job
admin.           10802
blue-collar       9605
technician        6984
services          4135
management        3036
retired           1782
entrepreneur      1509
self-employed     1483
housemaid         1117
unemployed        1059
student            896
unknown            344
Name: count, dtype: int64

## Marital

In [13]:
# En este caso como los NaN representan una parte ínfima de la población, los eliminaremos
# ya que pese a tener marital como NaN no parecen seguir ningún patron claro
display(df_bank_csv['marital'].value_counts(dropna=False))
display(df_bank_csv['marital'].isna().sum())
display(df_bank_csv[df_bank_csv['marital'].isna()].sample(5))

df_bank_csv = df_bank_csv.dropna(subset=['marital'])

display(df_bank_csv['marital'].value_counts(dropna=False))
display(df_bank_csv['marital'].isna().sum())

marital
MARRIED     25840
SINGLE      12043
DIVORCED     4784
NaN            85
Name: count, dtype: int64

np.int64(85)

,customer_id,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude
33209,86c465d2-c130-40b9-bf8c-971178dbf322,35,services,NaN,high.school,0.0,0.0,0.0,cellular,516,1,999,1,FAILURE,-1.8,"92,893","-46,2",-0.11,"5099,1",no,5-febrero-2019,40.493,-77.571
26097,1d9c3702-9a1d-49a0-993a-f6bfd1247bff,29,admin.,NaN,professional.course,0.0,1.0,0.0,cellular,125,1,999,1,FAILURE,-0.1,"93,2",-42,0.17,"5195,8",no,28-julio-2015,40.582,-74.216
32855,44e1ce4c-1e76-4730-9be7-cb808e68cac1,34,admin.,NaN,university.degree,0.0,1.0,0.0,cellular,447,2,999,0,NONEXISTENT,-1.8,"92,893","-46,2",-0.15,"5099,1",no,17-junio-2017,42.482,-119.634
11258,a404a390-bbe2-44c8-981f-f5792952c864,32,unknown,NaN,university.degree,0.0,0.0,0.0,telephone,36,7,999,0,NONEXISTENT,1.4,"94,465","-41,8",-0.19,"5228,1",no,29-abril-2018,44.592,-87.481
3381,4a0a8655-be76-4596-bdb4-7dd4ad738b9e,37,management,NaN,high.school,0.0,0.0,0.0,telephone,95,6,999,0,NONEXISTENT,1.1,"93,994","-36,4",-0.13,5191,no,10-diciembre-2018,26.706,-123.979

marital
MARRIED     25840
SINGLE      12043
DIVORCED     4784
Name: count, dtype: int64

np.int64(0)

## Education

In [14]:
# juntamos los rangos para no tener tantas categorías y así facilitar el análisis
# además los Nan faltantes los transformaremos a 'unknown' 
display(df_bank_csv['education'].value_counts(dropna=False))
display(df_bank_csv['education'].isna().sum())

df_bank_csv['education'] = df_bank_csv['education'].replace(['basic.4y', 'basic.6y', 'basic.9y'], 'basic')
df_bank_csv['education'] = df_bank_csv['education'].fillna('unknown')

display(df_bank_csv['education'].value_counts(dropna=False))
display(df_bank_csv['education'].isna().sum())

education
university.degree      12610
high.school             9857
basic.9y                6272
professional.course     5433
basic.4y                4325
basic.6y                2367
NaN                     1785
illiterate                18
Name: count, dtype: int64

np.int64(1785)

education
basic                  12964
university.degree      12610
high.school             9857
professional.course     5433
unknown                 1785
illiterate                18
Name: count, dtype: int64

np.int64(0)

## Housing

In [15]:
# vamos a rellenar los NaN de housing con la moda porque pese a ser una parte importante de la población como 
# los dos valores estan muy parejos no afectará mucho al análisis y así mantenemos la mayor cantidad de datos posible
display(df_bank_csv['housing'].value_counts(dropna=False))
display(df_bank_csv['housing'].isna().sum())

mode_housing = df_bank_csv['housing'].mode()[0]
df_bank_csv['housing'] = df_bank_csv['housing'].fillna(mode_housing)

display(df_bank_csv['housing'].value_counts(dropna=False))
display(df_bank_csv['housing'].isna().sum())

housing
1.0    22330
0.0    19320
NaN     1017
Name: count, dtype: int64

np.int64(1017)

housing
1.0    23347
0.0    19320
Name: count, dtype: int64

np.int64(0)

## Loan

In [16]:
# En este caso como los Nan estan en un campo más dispar en cuanto al resto de 
# valores (80 - 20 aprox) crearemos una nueva categoría -1 para los datos desconocidos
display(df_bank_csv['loan'].value_counts(dropna=False))
display(df_bank_csv['loan'].isna().sum())

df_bank_csv['loan'] = df_bank_csv['loan'].fillna(-1)

display(df_bank_csv['loan'].value_counts(dropna=False))
display(df_bank_csv['loan'].isna().sum())

loan
0.0    35174
1.0     6476
NaN     1017
Name: count, dtype: int64

np.int64(1017)

loan
 0.0    35174
 1.0     6476
-1.0     1017
Name: count, dtype: int64

np.int64(0)

## cons.price.idx

In [17]:
display(df_bank_csv['cons.price.idx'].value_counts(dropna=False))
display(df_bank_csv['cons.price.idx'].isna().sum())

df_bank_csv['cons.price.idx'] = df_bank_csv['cons.price.idx'].str.replace(',', '.', regex=False).astype(float)
df_bank_csv['cons.price.idx'] = df_bank_csv['cons.price.idx'].astype(float)

mean_value = df_bank_csv['cons.price.idx'].mean()
df_bank_csv['cons.price.idx'] = df_bank_csv['cons.price.idx'].fillna(mean_value)

display(df_bank_csv['cons.price.idx'].isna().sum())

cons.price.idx
93,994    7881
93,918    6889
92,893    5933
93,444    5303
94,465    4490
93,2      3705
93,075    2534
92,201     798
92,963     732
92,431     467
NaN        464
92,649     372
94,215     317
94,199     316
92,843     297
92,379     270
93,369     265
94,027     241
94,055     236
93,876     221
94,601     210
92,469     183
92,713     179
93,749     176
94,767     129
93,798      48
92,756      11
Name: count, dtype: int64

np.int64(464)

np.int64(0)

## Modificación de algunas columnas

In [18]:
# Eliminamos los decimales de nr.employed y lo convertimos a int ya que no puede existir media persona
df_bank_csv['nr.employed'] = df_bank_csv['nr.employed'].str.split(',').str[0].astype(int)

# Pasamos a float cons.conf.idx para poder utilizar correctamente la columna
df_bank_csv['cons.conf.idx'] = df_bank_csv['cons.conf.idx'].str.replace(',', '.', regex=False).astype(float)

# Dividir la columna date en tres columnas: day, month, year
df_bank_csv[['day','month','year']] = df_bank_csv['date'].str.split('-', expand=True)

df_bank_csv['day'] = df_bank_csv['day'].astype(int)
df_bank_csv['year'] = df_bank_csv['year'].astype(int)

meses = {
    'enero':1, 'febrero':2, 'marzo':3, 'abril':4,
    'mayo':5, 'junio':6, 'julio':7, 'agosto':8,
    'septiembre':9, 'octubre':10, 'noviembre':11, 'diciembre':12
}
df_bank_csv['month'] = df_bank_csv['month'].map(meses)

df_bank_csv['date_fixed'] = (
    df_bank_csv['day'].astype(str) + '-' + df_bank_csv['month'].astype(str) + '-' + df_bank_csv['year'].astype(str)
)

df_bank_csv['date'] = pd.to_datetime(
    df_bank_csv['date_fixed'],
    format='%d-%m-%Y'
)

df_bank_csv.drop(columns=['day', 'month', 'year', 'date_fixed'], inplace=True)

In [19]:
display(df_bank_csv.info())
display(df_bank_csv.sample(5))

<class 'pandas.DataFrame'>
Index: 42667 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     42667 non-null  str
 1   age             42667 non-null  int64
 2   job             42667 non-null  str
 3   marital         42667 non-null  str
 4   education       42667 non-null  str
 5   default         42667 non-null  float64
 6   housing         42667 non-null  float64
 7   loan            42667 non-null  float64
 8   contact         42667 non-null  str
 9   duration        42667 non-null  int64
 10  campaign        42667 non-null  int64
 11  pdays           42667 non-null  int64
 12  previous        42667 non-null  int64
 13  poutcome        42667 non-null  str
 14  emp.var.rate    42667 non-null  float64
 15  cons.price.idx  42667 non-null  float64
 16  cons.conf.idx   42667 non-null  float64
 17  euribor3m       42667 non-null  float64
 18  nr.employed     42667 non-null  int64
 19  y               42667 non-null  str
 20  date            42667 non-null  datetime64[us]
 21  latitude        42667 non-null  float64
 22  longitude       42667 non-null  float64
dtypes: datetime64[us](1), float64(9), int64(6), str(7)
memory usage: 11.3 MB

None

,customer_id,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude
35096,13a7b09f-9d49-4887-8951-4b804aa9f22e,31,unemployed,SINGLE,high.school,0.0,0.0,0.0,cellular,10,2,999,0,NONEXISTENT,-1.8,92.893,-46.2,-0.19,5099,no,2019-06-22,44.463,-124.222
1350,d8a01eb2-2a66-4924-b6e2-0bded8a4ae0f,39,admin.,MARRIED,basic,-1.0,1.0,0.0,telephone,617,2,999,0,NONEXISTENT,1.1,93.994,-36.4,-0.18,5191,no,2017-10-15,25.051,-90.315
22875,4f7690b4-86b8-4e96-ae45-65b555908343,57,admin.,MARRIED,high.school,-1.0,1.0,1.0,cellular,127,4,999,0,NONEXISTENT,1.4,93.444,-36.1,0.17,5228,no,2015-05-12,24.727,-109.740
20302,a65807ea-d134-4113-a595-55e17aad17c3,30,admin.,SINGLE,university.degree,0.0,0.0,0.0,cellular,365,1,999,0,NONEXISTENT,1.4,93.444,-36.1,-0.17,5228,no,2017-09-21,24.614,-117.602
42927,0217971e-bda1-4ae5-9111-63c70db532e7,24,technician,SINGLE,basic,0.0,0.0,0.0,cellular,87,3,999,0,NONEXISTENT,-1.8,92.893,-46.2,-0.01,5099,no,2016-04-09,30.687,-106.174

In [20]:
display(df_final.info())
display(df_final.sample(5))

<class 'pandas.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[us]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  str
 7   year               43170 non-null  int64
 8   month              43170 non-null  int32
dtypes: datetime64[us](1), int32(1), int64(6), str(1)
memory usage: 4.3 MB

None

,customer_id,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID,year,month
8858,8858,104093,0,1,2012-09-22,22,cd1ad70f-548d-4387-a2ee-a763341fbff6,2012,9
31543,2463,53907,1,0,2014-08-08,14,8e2a14a8-7caf-4b2d-bb71-164da5fd2d8d,2014,8
35045,5965,166726,2,2,2014-02-28,10,52be3e86-59ec-4d6f-956c-512ecd7f3c94,2014,2
15444,15444,91447,0,1,2012-01-05,15,8234e450-e484-40f1-a8b8-2cf72f0d23ea,2012,1
40367,11287,66056,0,2,2014-05-25,8,05b01f4c-0e66-4e1a-b388-1e39694ce177,2014,5

In [21]:
# exportamos los dos datasets limpios a csv
df_bank_csv.to_csv('cleaned_csv/bank_additional_cleaned.csv', index=False)
df_final.to_csv('cleaned_csv/customer_details_cleaned.csv', index=False)